### ISSUE TITLE
Error replicating NICA

### ISSUE THREAD

**Issue by hamedsey** [acsl-technion/nica#2]
Dear Haggai,

My name is Hamed. First off, I wanted to say your work is super interesting and inspiring! I'm interested to use NICA for my research, specifically your custom ring implementation any how you interface with userspace queues.

I'm currently trying to replicate the C-Simulation and C/RTL co-simulation, but have hit a roadblock while running "make check" to run C-simulation for all ikernels. There is one error: **nethome/hseyedro3/nica_workspace/nica/ntl/ntl/counter.hpp:34:31: error: expected ')' before 'v'
         INLINE maxed_int(TYPE v) : base(v) {}**

I've also included the full log below, in case it may help:

`hseyedro3@keg5:~/nica_workspace/nica/build$ make check
[  6%] Built target cms-emu
Scanning dependencies of target nica-csim
make[3]: Warning: File 'nica/CMakeFiles/nica-csim.dir/depend.make' has modification time 0.042 s in the future
[  7%] Building CXX object nica/CMakeFiles/nica-csim.dir/hls/nica.cpp.o
In file included from /nethome/hseyedro3/nica_workspace/nica/ntl/ntl/enumerate.hpp:3:0,
                 from /nethome/hseyedro3/nica_workspace/nica/nica/hls/mlx.h:31,
                 from /nethome/hseyedro3/nica_workspace/nica/nica/hls/udp.h:39,
                 from /nethome/hseyedro3/nica_workspace/nica/nica/hls/nica.cpp:28:
nethome/hseyedro3/nica_workspace/nica/ntl/ntl/counter.hpp:34:31: error: expected ')' before 'v'
         INLINE maxed_int(TYPE v) : base(v) {}
                               ^
/nethome/hseyedro3/nica_workspace/nica/ntl/ntl/counter.hpp:46:9: note: in expansion of macro 'CTOR'
         CTOR(half)
         ^
In file included from /nethome/hseyedro3/nica_workspace/nica/nica/hls/flow_table_impl.hpp:34:0,
                 from /nethome/hseyedro3/nica_workspace/nica/nica/hls/udp.h:45,
                 from /nethome/hseyedro3/nica_workspace/nica/nica/hls/nica.cpp:28:
/nethome/hseyedro3/nica_workspace/nica/ntl/ntl/cache.hpp: In instantiation of 'ntl::cache<Tag, Value, Size, max_hops, insert_overrides>::cache() [with Tag = flow; Value = flow_table_value; unsigned int Size = 1024u; int max_hops = 1; bool insert_overrides = false]':
/nethome/hseyedro3/nica_workspace/nica/ntl/ntl/cache.hpp:212:39:   required from 'ntl::hash_table_wrapper<Tag_type, Mapped_type, Size>::hash_table_wrapper() [with Tag_type = flow; Mapped_type = flow_table_value; unsigned int Size = 1024u]'
/nethome/hseyedro3/nica_workspace/nica/nica/hls/flow_table_impl.hpp:157:18:   required from here
/nethome/hseyedro3/nica_workspace/nica/ntl/ntl/cache.hpp:54:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (int i = 0; i < Size; ++i) {
                               ^
In file included from /nethome/hseyedro3/nica_workspace/nica/nica/hls/nica-impl.hpp:29:0,
                 from /nethome/hseyedro3/nica_workspace/nica/nica/hls/nica.cpp:31:
/nethome/hseyedro3/nica_workspace/nica/nica/hls/demux.hpp: In instantiation of 'demultiplexor<num_ports>::index_t demultiplexor<num_ports>::select_port(const udp_builder_metadata&) [with unsigned int num_ports = 3u; demultiplexor<num_ports>::index_t = ap_uint<2>; udp::udp_builder_metadata = hls_ik::metadata]':
/nethome/hseyedro3/nica_workspace/nica/nica/hls/demux.hpp:74:40:   required from 'void demultiplexor<num_ports>::port_selector() [with unsigned int num_ports = 3u]'
/nethome/hseyedro3/nica_workspace/nica/nica/hls/demux.hpp:52:22:   required from 'void demultiplexor<num_ports>::demux(demultiplexor<num_ports>::metadata_stream&, demultiplexor<num_ports>::stream&, tc_ports&) [with unsigned int num_ports = 3u; demultiplexor<num_ports>::metadata_stream = hls::stream<ap_uint<250> >; demultiplexor<num_ports>::stream = hls::stream<ap_uint<289> >]'
/nethome/hseyedro3/nica_workspace/nica/nica/hls/nica.cpp:221:16:   required from 'void nica_state<pipeline>::nica_step(mlx::stream&, mlx::stream&, nica_state<pipeline>::config&, nica_pipeline_stats&, hls_ik::trace_event*, hls_ik::ports&, tc_ports&, tc_ports&) [with hls_ik::pipeline_ports hls_ik::ports::* pipeline = &hls_ik::ports::net; mlx::stream = hls::stream<mlx::axi4s>; nica_state<pipeline>::config = udp::config_n2h; hls_ik::trace_event = ap_uint<1>]'
/nethome/hseyedro3/nica_workspace/nica/nica/hls/nica.cpp:289:16:   required from here
/nethome/hseyedro3/nica_workspace/nica/nica/hls/demux.hpp:175:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (ik_id >= num_ports) {
                   ^
nica/CMakeFiles/nica-csim.dir/build.make:62: recipe for target 'nica/CMakeFiles/nica-csim.dir/hls/nica.cpp.o' failed
make[3]: *** [nica/CMakeFiles/nica-csim.dir/hls/nica.cpp.o] Error 1
CMakeFiles/Makefile2:239: recipe for target 'nica/CMakeFiles/nica-csim.dir/all' failed
make[2]: *** [nica/CMakeFiles/nica-csim.dir/all] Error 2
CMakeFiles/Makefile2:86: recipe for target 'CMakeFiles/check.dir/rule' failed
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
Makefile:129: recipe for target 'check' failed
make: *** [check] Error 2`

I followed the instructions listed on your GitHub step-by-step, but not sure if this may be an error with my environment setup. Have you ever come across this?

Any advice would be much appreciated!

Thank you, in advance,
Hamed

**Comment by haggaie** [comment]
Hi Hamed,

Thank you for your interest. I seem to recall this error from using different versions of Xilinx Vivado HLS. Could you tell me what version are you using, and which branch of the code did you try?

**Comment by hamedsey** [comment]
Thanks for your reply. I've installed Vivado HLS 2016.2 and I'm using the master branch of the code.

**Comment by haggaie** [comment]
I think the master branch was tested with Vivado HLS 2018.2. Could you try that version? 

I'm not sure, but I believe this error is caused by `maxed_int` constructors. One of them might be using a type that was defined only in 2018.2 (perhaps `half`). You could try removing it, although there could be other issues with 2016.2.

Another option is to take one of the older branches, such as `threshold`. I think it was tested with 2016.2.

**Comment by hamedsey** [comment]
Thank you for the tip, Haggai! I was able to get past that stage by installing Vivado 2018.2. I have a few follow-up questions on the custom-ring implementation in NICA.

1. How does NICA expose the custom rings to cores and allow the FPGA to send messages to those rings?
2. I've noticed in the HLS files pertaining to the custom ring implementation, there’s a RoCE frame that is being constructed. Does that determine which custom ring the data is written to?

**Comment by haggaie** [comment]
> I was able to get past that stage by installing Vivado 2018.2. 

I'm glad to hear that.

> How does NICA expose the custom rings to cores and allow the FPGA to send messages to those rings?

Custom rings are created as RDMA queue pairs on the host. You can see the relevant code in the libnica code for the custom_ring_create function.

> I've noticed in the HLS files pertaining to the custom ring implementation, there’s a RoCE frame that is being constructed. Does that determine which custom ring the data is written to?

Yes, the FPGA sends RoCE frames to the NIC, and the NIC uses the destination QP number in the frame to determine on which QP to use.
